package `in`.gopalpoddar.textspur.features.chat.chatroom.presentation

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import dagger.hilt.android.lifecycle.HiltViewModel
import `in`.gopalpoddar.textspur.features.auth.login.domain.repository.AuthRepository
import `in`.gopalpoddar.textspur.features.chat.chatroom.domain.usecase.ObserveMessagesUseCase
import `in`.gopalpoddar.textspur.features.chat.chatroom.domain.usecase.ObserveParticipantUseCase
import `in`.gopalpoddar.textspur.features.chat.chatroom.domain.usecase.SendMessageUseCase
import `in`.gopalpoddar.textspur.features.chat.home.domain.model.Message

import `in`.gopalpoddar.textspur.features.profile.domain.repository.UserRepository
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.catch
import kotlinx.coroutines.flow.launchIn
import kotlinx.coroutines.flow.onEach
import kotlinx.coroutines.flow.update
import kotlinx.coroutines.launch
import javax.inject.Inject

@HiltViewModel
class ChatRoomViewModel @Inject constructor(
    private val authRepository: AuthRepository,
    private val userRepository: UserRepository,
    private val observeMessagesUseCase: ObserveMessagesUseCase,
    private val observeParticipantUseCase: ObserveParticipantUseCase,
    private val sendMessageUseCase: SendMessageUseCase
) : ViewModel() {

    private val _state = MutableStateFlow(ChatRoomState())
    val state: StateFlow<ChatRoomState> = _state.asStateFlow()

    private var currentChatId: String? = null
    private var otherUserId: String? = null

    init {
        val currentUserId = authRepository.getCurrentUserId()
        _state.update { it.copy(currentUserId = currentUserId) }
    }

    fun initChat(chatId: String) {
        if (currentChatId == chatId) return // Already initialized
        currentChatId = chatId
        
        val currentUserId = _state.value.currentUserId ?: return
        
        // Derive otherUserId
        val uids = chatId.split("_")
        otherUserId = if (uids.size == 2) {
            if (uids[0] == currentUserId) uids[1] else uids[0]
        } else {
            null
        }

        if (otherUserId == null) {
            _state.update { it.copy(error = "Invalid Chat ID", isLoading = false) }
            return
        }
        
        // Fetch user profile instantly to avoid "Loading..." while realtime listener connects
        viewModelScope.launch {
            val result = userRepository.getCurrentUserProfile(otherUserId!!)
            if (result.isSuccess) {
                val profile = result.getOrThrow()
                _state.update { 
                    it.copy(
                        otherParticipant = profile
                    ) 
                }
            }
        }
        
        observeParticipant(chatId, otherUserId!!)
        observeMessages(chatId)
    }

    private fun observeParticipant(chatId: String, participantId: String) {
        observeParticipantUseCase(chatId, participantId)
            .onEach { participant ->
                _state.update { it.copy(otherParticipant = participant) }
            }
            .launchIn(viewModelScope)
    }

    private fun observeMessages(chatId: String) {
        observeMessagesUseCase(chatId)
            .onEach { messages ->
                _state.update { it.copy(messages = messages, isLoading = false, error = null) }
            }
            .catch { e ->
                _state.update { it.copy(error = e.message, isLoading = false) }
            }
            .launchIn(viewModelScope)
    }

    fun onMessageChange(text: String) {
        _state.update { it.copy(messageText = text) }
    }

    fun sendMessage() {
        val text = _state.value.messageText.trim()
        if (text.isEmpty()) return

        val currentUserId = _state.value.currentUserId ?: return
        val receiverId = otherUserId ?: return
        val chatId = currentChatId ?: return

        val message = Message(
            id = "", // Will be generated by Data Source
            message = text,
            read = false,
            receiverId = receiverId,
            senderId = currentUserId,
            timestamp = System.currentTimeMillis()
        )

        // Clear input immediately for better UX
        _state.update { it.copy(messageText = "") }

        viewModelScope.launch {
            val result = sendMessageUseCase(chatId, message)
            if (result.isFailure) {
                // Optionally restore message if failed, or show error
                _state.update { it.copy(error = "Failed to send message: ${result.exceptionOrNull()?.message}") }
            }
        }
    }
}
